from __future__ import annotations


def render_dashboard() -> str:
    """Return the dependency-free V1 operator/developer dashboard."""

    return r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>IndusTSFM Studio</title>
<style>
:root{--bg:#f3f6fa;--panel:#fff;--ink:#172033;--muted:#667085;--line:#d8e0e9;--nav:#0b1726;--nav2:#132c46;--accent:#1e6eea;--good:#087a55;--warn:#b75f00;--bad:#b42318}
*{box-sizing:border-box} body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif}
.shell{display:grid;grid-template-columns:236px 1fr;min-height:100vh}.side{background:linear-gradient(180deg,var(--nav),var(--nav2));color:#dbe7f3;padding:22px 16px;position:sticky;top:0;height:100vh}.brand{font-weight:800;font-size:20px;color:#fff;padding:4px 8px 20px}.brand small{display:block;font-size:10px;letter-spacing:.12em;color:#8fb3d8;margin-top:4px}.nav a{display:block;color:#bcd0e3;text-decoration:none;padding:10px 12px;border-radius:8px;margin:3px 0}.nav a:hover,.nav a.active{background:#ffffff12;color:#fff}.main{padding:22px 28px 60px;min-width:0}.top{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:18px}.top h1{font-size:24px;margin:0}.top p{margin:2px 0 0;color:var(--muted)}.status{padding:6px 10px;border:1px solid #bfe4d6;background:#edf9f4;border-radius:999px;color:var(--good);font-weight:700}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.card,.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;box-shadow:0 2px 8px #10243c0a}.card{padding:15px}.k{font-size:12px;color:var(--muted)}.v{font-size:23px;font-weight:750;margin-top:4px}.panel{margin-top:14px;padding:17px}.panel h2{font-size:17px;margin:0 0 12px}.two{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:9px 8px;border-bottom:1px solid var(--line);white-space:nowrap;vertical-align:top}.table th{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}.scroll{overflow:auto}.pill{display:inline-block;background:#edf4ff;color:#245da8;padding:3px 8px;border-radius:999px;font-size:11px;margin:2px}.pill.good{background:#edf9f4;color:var(--good)}.pill.warn{background:#fff5e8;color:var(--warn)}.pill.bad{background:#fff0ee;color:var(--bad)}.empty{color:var(--muted);padding:18px 4px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.foot{margin-top:18px;color:var(--muted);font-size:12px}.bar{height:8px;background:#e7edf3;border-radius:999px;overflow:hidden}.bar>i{display:block;height:100%;background:linear-gradient(90deg,#1e6eea,#17a67a)}.btn{border:1px solid #cbd5e1;background:#fff;color:#25364d;border-radius:7px;padding:6px 9px;font-weight:650;cursor:pointer;margin:2px}.btn:hover{border-color:#91a4ba;background:#f7f9fc}.btn.primary{background:#1e6eea;color:#fff;border-color:#1e6eea}.btn.danger{color:var(--bad);border-color:#efc4bf}.btn:disabled{opacity:.45;cursor:not-allowed}.preview{background:#0f172a;color:#d7e2f0;border-radius:9px;padding:12px;max-height:260px;overflow:auto;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap}.subhead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:8px}.muted{color:var(--muted)}
@media(max-width:950px){.shell{grid-template-columns:1fr}.side{display:none}.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}.main{padding:18px}}
</style>
</head>
<body>
<div class="shell">
<aside class="side"><div class="brand">IndusTSFM<small>INDUSTRIAL INTELLIGENCE STUDIO</small></div><nav class="nav"><a class="active" href="#overview">Overview</a><a href="#projects">Projects</a><a href="#analytics">Analytics</a><a href="#models">Model Hub</a><a href="#applications">Applications</a><a href="#connectors">Data Sources</a><a href="#opcua">OPC-UA Live</a><a href="#runtime">Runtime</a></nav></aside>
<main class="main">
<div class="top"><div><h1>Industrial Time-Series Intelligence</h1><p>Data audit → analytics → AutoModel → anomaly triage → application runtime</p></div><span id="health" class="status">checking</span></div>
<section id="overview" class="grid"><div class="card"><div class="k">Projects</div><div id="projectCount" class="v">—</div></div><div class="card"><div class="k">Applications</div><div id="appCount" class="v">—</div></div><div class="card"><div class="k">Implemented models</div><div id="modelCount" class="v">—</div></div><div class="card"><div class="k">Analytics tools</div><div id="analyticsCount" class="v">—</div></div><div class="card"><div class="k">Product routes</div><div id="routeCount" class="v">—</div></div><div class="card"><div class="k">Active OPC-UA</div><div id="opcuaRuntimeCount" class="v">—</div></div></section>
<div class="two">
<section id="projects" class="panel"><h2>Projects</h2><div id="projectTable" class="scroll empty">Loading…</div></section>
<section id="connectors" class="panel"><h2>Data connectors</h2><div id="connectorsBody" class="empty">Loading…</div></section>
</div>
<section id="opcua" class="panel"><div class="subhead"><div><h2>OPC-UA Live</h2><div id="opcuaCapability" class="muted">Checking read-only live extension…</div></div><button id="opcuaRefresh" class="btn">Refresh</button></div><div id="opcuaTable" class="scroll empty">Loading configured OPC-UA sources…</div><h2 style="margin-top:18px">Snapshot preview</h2><pre id="opcuaPreview" class="preview">Select Snapshot on a configured source. Values, source/server timestamps and quality are shown without interpolation.</pre><p class="foot">Safety boundary: Studio can browse/read/subscribe only. OPC-UA writes, setpoint changes and closed-loop control are not exposed.</p></section>
<section id="analytics" class="panel"><h2>Industrial analytics</h2><div id="analyticsBody" class="empty">Loading…</div><p class="foot">Lag analysis is association-only; shift analytics use source/reference statistics; variable discovery is a transparent screening heuristic, not causal discovery.</p></section>
<section id="models" class="panel"><h2>Model Hub</h2><div id="modelTable" class="scroll empty">Loading…</div></section>
<section id="applications" class="panel"><h2>Applications</h2><div id="appTable" class="scroll empty">Loading…</div></section>
<section id="runtime" class="panel"><h2>Runtime boundary</h2><p>V1 supports deterministic offline replay plus strictly read-only OPC-UA live acquisition. Live samples retain arrival order, OPC-UA quality and source/server timestamps; hidden interpolation/resampling is not performed. MQTT remains contract-only and closed-loop OT control remains disabled.</p><div class="bar"><i style="width:72%"></i></div><div class="foot">Productization sequence: deterministic numerical layer → live industrial runtime → streaming inference → UQ/diagnosis/optimization → Agent orchestration.</div></section>
</main></div>
<script>
const esc=x=>String(x??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function request(path,options={}){const r=await fetch(path,options);let body=null;const text=await r.text();if(text){try{body=JSON.parse(text)}catch(_){body=text}}if(!r.ok){const detail=body?.detail||body||('HTTP '+r.status);throw new Error(String(detail))}return body}
const get=path=>request(path);
const post=path=>request(path,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});
function table(rows,cols){if(!rows.length)return '<div class="empty">No records yet.</div>';return '<table class="table"><thead><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+(c[2]?c[1](r):esc(c[1](r)))+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function statePill(state){const s=String(state||'disconnected');const cls=s==='running'?'good':(s==='reconnecting'||s==='starting'?'warn':(s==='cancelled'?'bad':''));return '<span class="pill '+cls+'">'+esc(s)+'</span>'}
function configuredOpcua(projects){const rows=[];for(const project of projects||[]){const spec=project.spec||{};for(const source of spec.data_sources||[]){if(String(source.kind||'').toLowerCase()==='opcua'){rows.push({project_id:project.project_id,project_name:spec.name||project.project_id,source_name:source.name,endpoint:source.location||'',tag_count:Object.keys(source.metadata?.node_ids||{}).length})}}}return rows}
let currentProjects=[];let opcuaLiveAvailable=false;
async function refreshOpcua(){const sources=configuredOpcua(currentProjects);let caps=null,runtimes=[];try{caps=await get('/v1/opcua/capabilities');const payload=await get('/v1/opcua/runtimes');runtimes=payload.runtimes||[];opcuaLiveAvailable=true}catch(e){opcuaLiveAvailable=false;document.getElementById('opcuaCapability').textContent='Live extension is not attached to this server process.';document.getElementById('opcuaRuntimeCount').textContent='0'}
if(caps){document.getElementById('opcuaCapability').innerHTML='<span class="pill good">read-only live v1</span> asyncua '+(caps.dependency_available?'available':'not installed')+' · writes disabled';document.getElementById('opcuaRuntimeCount').textContent=runtimes.filter(r=>!r.task_done).length}
const enriched=sources.map(s=>{const rt=runtimes.find(r=>String(r.project_id||'')===String(s.project_id)&&r.source_name===s.source_name&&!r.task_done)||runtimes.find(r=>String(r.project_id||'')===String(s.project_id)&&r.source_name===s.source_name);return {...s,runtime:rt}});
document.getElementById('opcuaTable').className='scroll';document.getElementById('opcuaTable').innerHTML=table(enriched,[['Project',r=>r.project_name],['Source',r=>r.source_name],['Endpoint',r=>'<span class="mono">'+esc(r.endpoint)+'</span>',true],['State',r=>statePill(r.runtime?.state?.status||'disconnected'),true],['Configured',r=>r.runtime?.connection?.configured_node_count??r.tag_count],['Subscribed',r=>r.runtime?.state?.subscribed_tag_count??0],['Samples',r=>r.runtime?.state?.samples_received??0],['Dropped',r=>r.runtime?.buffer?.dropped_rows??0],['Bad quality',r=>r.runtime?.state?.bad_quality_samples??0],['Disconnects',r=>r.runtime?.state?.disconnects??0],['Reconnects',r=>r.runtime?.state?.reconnects??0],['Gap s',r=>r.runtime?.state?.data_gap_seconds!=null?Number(r.runtime.state.data_gap_seconds).toFixed(2):'0.00'],['Last sample',r=>r.runtime?.state?.last_sample_at||'—'],['Actions',r=>{const snap='<button class="btn" data-opcua="snapshot" data-project="'+esc(r.project_id)+'" data-source="'+esc(r.source_name)+'">Snapshot</button>';if(!opcuaLiveAvailable)return snap;const rt=r.runtime;if(rt&&!rt.task_done&&rt.state?.status!=='stopped')return snap+'<button class="btn danger" data-opcua="stop" data-runtime="'+esc(rt.runtime_id)+'">Stop</button>';return snap+'<button class="btn primary" data-opcua="start" data-project="'+esc(r.project_id)+'" data-source="'+esc(r.source_name)+'">Start</button>'},true]]);bindOpcuaActions()}
function bindOpcuaActions(){document.querySelectorAll('[data-opcua]').forEach(btn=>btn.addEventListener('click',async()=>{const action=btn.dataset.opcua;btn.disabled=true;try{if(action==='start'){await post('/v1/projects/'+encodeURIComponent(btn.dataset.project)+'/opcua/'+encodeURIComponent(btn.dataset.source)+'/live/start')}else if(action==='stop'){await post('/v1/opcua/runtimes/'+encodeURIComponent(btn.dataset.runtime)+'/stop')}else if(action==='snapshot'){const result=await post('/v1/projects/'+encodeURIComponent(btn.dataset.project)+'/opcua/'+encodeURIComponent(btn.dataset.source)+'/snapshot');document.getElementById('opcuaPreview').textContent=JSON.stringify(result,null,2)}await refreshOpcua()}catch(e){document.getElementById('opcuaPreview').textContent=action+' failed: '+e.message}finally{btn.disabled=false}}))}
async function boot(){try{const [h,c,p,a]=await Promise.all([get('/health'),get('/v1/capabilities'),get('/v1/projects'),get('/v1/applications')]);currentProjects=p.projects||[];document.getElementById('health').textContent=h.status==='ok'?'API healthy':'degraded';document.getElementById('projectCount').textContent=p.count;document.getElementById('appCount').textContent=a.count;document.getElementById('modelCount').textContent=c.models.length;document.getElementById('analyticsCount').textContent=c.analytics.length;document.getElementById('routeCount').textContent=c.implemented_product_routes.length;
document.getElementById('projectTable').className='scroll';document.getElementById('projectTable').innerHTML=table(p.projects,[['Project',r=>r.spec?.name],['ID',r=>r.project_id],['Tasks',r=>r.spec?.tasks?.length??0],['Updated',r=>r.updated_at]]);
document.getElementById('modelTable').className='scroll';document.getElementById('modelTable').innerHTML=table(c.models,[['Model',r=>r.name],['Family',r=>r.family],['Tasks',r=>r.task_types?.join(', ')],['Mode',r=>r.training_modes?.join(', ')],['Multivariate',r=>r.native_multivariate?'yes':'no']]);
document.getElementById('appTable').className='scroll';document.getElementById('appTable').innerHTML=table(a.applications,[['Application',r=>r.application_id],['Status',r=>r.status],['Task',r=>r.task],['Model',r=>r.selected_model],['Strategy',r=>r.selected_strategy]]);
document.getElementById('connectorsBody').className='';document.getElementById('connectorsBody').innerHTML='<div>'+c.data_source_contracts.map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</div><p class="foot">Implemented local: '+esc(c.implemented_local_connectors.join(', '))+' · OPC-UA: read-only live extension · MQTT: contract-only</p>';
document.getElementById('analyticsBody').className='';document.getElementById('analyticsBody').innerHTML='<div>'+c.analytics.map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</div>';await refreshOpcua();if(opcuaLiveAvailable)setInterval(refreshOpcua,3000)
}catch(e){document.getElementById('health').textContent='API error';document.getElementById('health').style.color='var(--warn)';console.error(e)}}document.getElementById('opcuaRefresh').addEventListener('click',refreshOpcua);boot();
</script>
</body></html>'''
